To be checked step 2
User8956/DotNext-Moscow-2020 pull request #3
Opened 2021-03-04 07:56 UTC by User8956

From step-1 to step-2

2021-03-07 09:28 UTC, max-arshinov requested changes

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/CompleteOrder/CompleteOrderAdminCommand.cs
> +        public int   OrderId { get; set; }
Привыкайте исправлять ошибки форматирования, даже если они были до вас

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersHandler.cs
> +            (IEnumerable<OrderListItem>)_orders
Да нет же. ToList нужно взывать. Вы возвращаете энумератор, который в foreach будет делать запрос к БД на каждом шаге цикла

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersQueryHandler.cs
> +              (IEnumerable<OrderListItem>)_orders
Аналогично

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetOrders/GetOrdersHandler.cs
> +            return (IQueryable<OrderListItem>)_orders
Зачем это приведение типов?

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/ShipOrder/ShipOrderCommand.cs
> +        public int   OrderId { get; set; }
Аналогично про форматирование

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Cart/AddItem/AddToCartCommand.cs
> +        public int ProductID { get; private set; }
ProductId

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Catalog/GetProducts/GetProductsQueryHandler.cs
> +            var products = _products
зачем вы два раза делаете проекцию? Где ToList?

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Index/GetBestsellers/GetBesellersQueryHandler.cs
> +                .ProjectToType<BestsellersListItem>().ToList();
Перенести .ToList на новую строчку

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Index/IndexController.cs
> +        /*[ProducesResponseType(typeof(NewArrivalsListItem), StatusCodes.Status200OK)]*/
Удалить

2021-03-07 09:28 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/UserOrders/CompleteOrder/CompleteOrderCommand.cs
> +    public class CompleteOrderCommand : ChangeOrderStateBase
OrderId лучше перенести в базовый класс, чтобы устранить дублирование кода

2021-03-07 10:27 UTC, max-arshinov requested changes

2021-03-07 10:27 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersQueryHandler.cs
> +              (IEnumerable<OrderListItem>)_orders
Уберите каст к  (IEnumerable<OrderListItem>). Он не нужен

2021-03-07 10:27 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetOrders/GetOrdersHandler.cs
> +            return (IEnumerable<OrderListItem>)_orders
Каст не нужен

2021-03-07 10:30 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersHandler.cs
> +            (IEnumerable<OrderListItem>)_orders
Каст все еще не нужен

2021-03-07 10:40 UTC, User8956 commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersQueryHandler.cs
> +              (IEnumerable<OrderListItem>)_orders
У меня студия ругается: "Error CS0266	Cannot implicitly convert type"

2021-03-14 08:51 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetAllOrders/GetAllOrdersQueryHandler.cs
> +              (IEnumerable<OrderListItem>)_orders
Смотрите какой тип возвращает AllOrdersItem.Map. Похоже там не тот, и у вас Runtime Exception здесь, который вы не проверили. Каст не нужен

2021-03-14 08:51 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Admin/GetOrders/GetOrdersHandler.cs
> +            return (IEnumerable<OrderListItem>)_orders
Аналогично

2021-03-14 08:51 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Index/GetBestsellers/GetBesellersQueryHandler.cs
> +                .ProjectToType<BestsellersListItem>().ToList();
Не исправлено

2021-03-14 08:51 UTC, max-arshinov requested changes

2021-03-14 08:51 UTC, max-arshinov commented on Apps/HightechAngular.Web/Areas/Index/IndexController.cs
> +        /*[ProducesResponseType(typeof(NewArrivalsListItem), StatusCodes.Status200OK)]*/
Не исправлено

2021-03-14 09:52 UTC, merged